In [1]:
import numpy as np

arr = np.random.randint(1, 51, size=(5, 5))
print("Original array:\n", arr)

row_sums = arr.sum(axis=1)
max_row_index = np.argmax(row_sums)

print("\nRow sums:", row_sums)
print("Row with maximum sum:", arr[max_row_index])

# Replace all elements greater than the mean with 0
mean_value = arr.mean()
modified_arr = arr.copy()
modified_arr[modified_arr > mean_value] = 0

print("\nMean:", mean_value)
print("Modified array:\n", modified_arr)

Original array:
 [[ 5  6 32 43  6]
 [10 20 37 34 20]
 [25  3 33 19 16]
 [16 37 12 14 47]
 [ 5 33 37 23 22]]

Row sums: [ 92 121  96 126 120]
Row with maximum sum: [16 37 12 14 47]

Mean: 22.2
Modified array:
 [[ 5  6  0  0  6]
 [10 20  0  0 20]
 [ 0  3  0 19 16]
 [16  0 12 14  0]
 [ 5  0  0  0 22]]
